import { chatbotService } from './api';

/**
 * AI Service for Gemini LLM Chatbot
 */
export const processChatMessage = async (session, message, label = null) => {
  try {
    const payload = label !== null ? label : message;
    const response = await chatbotService.sendMessage(payload, null);
    
    // The backend now returns { text } directly generated by Gemini
    return {
      text: response.data.text
    };
  } catch (error) {
    console.error('AI Service Error:', error);
    if (error.response && error.response.data && error.response.data.text) {
      return { text: error.response.data.text };
    }
    return {
      text: 'A technical error occurred connecting to the assistant. Please try again later.'
    };
  }
};
